const PRODUCTS = [
  // ── MERMELADAS ──────────────────────────────────────────────
  {
    id: 'mermelada-tomate',
    name: 'Mermelada de Tomate',
    category: 'mermelada',
    icon: '🍅',
    image: 'assets/img/producto_tomate_actualizado.png',
    price: 5000,
    oldPrice: 6000,
    weight: '360 cc',
    badge: '🍅 En temporada',
    tagline: 'Dulce y salada a la vez. Perfecta con quesos.',
    description: 'Una de nuestras recetas más originales. El tomate rojo de temporada, cocinado lentamente con azúcar y limón, se transforma en una mermelada de sabor único: dulce, con acidez suave y un aroma inconfundible. Sorprende a todos.',
    ingredients: ['Tomate fresco', 'Azúcar', 'Jugo de limón'],
    uses: ['Bruschettas con queso de cabra', 'Con tablas de quesos', 'En sándwiches artesanales', 'Acompañando empanadas'],
    season: 'Verano · Enero a Marzo',
  },
  {
    id: 'mermelada-frutilla',
    name: 'Mermelada de Frutilla',
    category: 'mermelada',
    icon: '🍓',
    image: null,
    price: 6000,
    weight: '360 cc',
    badge: '🍓 En temporada',
    tagline: 'Clásica y aromática. La más querida de la feria.',
    description: 'Nuestra mermelada de frutilla es el clásico por excelencia. Elaborada con frutillas frescas de temporada seleccionadas en su punto justo de madurez, azúcar y un toque de limón. Perfecta para tostadas, tartas, yogur o como base de postres.',
    ingredients: ['Frutilla fresca', 'Azúcar', 'Jugo de limón'],
    uses: ['Tostadas y medialunas', 'Tarta de frutas', 'Yogur o granola', 'Relleno de alfajores'],
    season: 'Verano · Octubre a Enero',
  },
  {
    id: 'mermelada-durazno',
    name: 'Mermelada de Durazno',
    category: 'mermelada',
    icon: '🍑',
    image: null,
    price: 6000,
    weight: '360 cc',
    tagline: 'El sabor del verano en un frasco.',
    description: 'Duraznos maduros de la región convertidos en una mermelada suave, perfumada y llena de color. Su textura sedosa y su sabor dulce-ácido la hacen ideal para el desayuno o para acompañar quesos.',
    ingredients: ['Durazno fresco', 'Azúcar', 'Jugo de limón'],
    uses: ['Desayuno con manteca', 'Con queso crema', 'Budines y tortas', 'Helados caseros'],
    season: 'Verano · Diciembre a Febrero',
  },
  {
    id: 'mermelada-ciruela',
    name: 'Mermelada de Ciruela',
    category: 'mermelada',
    icon: '🍇',
    image: 'assets/img/producto_ciruela.png',
    price: 6000,
    weight: '360 cc',
    tagline: 'Intensa y ligeramente ácida. Ideal para glasear carnes.',
    description: 'Las ciruelas le dan a esta mermelada un color intenso y un sabor profundo con un toque ácido que la hace única. Perfecta tanto para el desayuno como para glasear carnes al horno.',
    ingredients: ['Ciruela fresca', 'Azúcar', 'Jugo de limón'],
    uses: ['Glaseado para pollo o cerdo', 'Con pan de campo', 'Relleno de facturas', 'Combinada con queso azul'],
    season: 'Verano-Otoño · Enero a Marzo',
  },
  {
    id: 'mermelada-higo',
    name: 'Mermelada de Higo',
    category: 'mermelada',
    icon: '🌿',
    image: 'assets/img/producto_higos.png',
    price: 6000,
    weight: '360 cc',
    tagline: 'Profunda y suave. Maridaje ideal con quesos maduros.',
    description: 'Los higos maduros tienen un sabor naturalmente dulce y complejo que se intensifica al cocinarse. Esta mermelada es densa, con pequeñas semillas que aportan textura, y un aroma que recuerda al jardín en verano.',
    ingredients: ['Higo fresco', 'Azúcar', 'Jugo de limón'],
    uses: ['Tabla de quesos maduros', 'Con brie o camembert', 'Sobre tostadas con ricotta', 'Postres finos'],
    season: 'Verano · Enero a Febrero',
  },
  {
    id: 'mermelada-mango-pera',
    name: 'Mermelada de Mango y Pera',
    category: 'mermelada',
    icon: '🥭',
    image: 'assets/img/producto_mango_pera.png',
    price: 6000,
    weight: '360 cc',
    badge: '🥭 En temporada',
    tagline: 'Exótica y tropical. Combinación sorprendente.',
    description: 'La dulzura tropical del mango encuentra a la suavidad de la pera en esta mermelada de edición especial. Un sabor frutal, fragante y diferente que conquista desde la primera cucharada.',
    ingredients: ['Mango fresco', 'Pera', 'Azúcar', 'Jugo de limón'],
    uses: ['Desayuno gourmet', 'Con yogur natural', 'Relleno de crepes', 'Acompañando pollo grillado'],
    season: 'Verano · Diciembre a Febrero',
  },
  {
    id: 'mermelada-membrillo-pera',
    name: 'Mermelada de Membrillo y Pera',
    category: 'mermelada',
    icon: '🍐',
    image: null,
    price: 6000,
    weight: '360 cc',
    tagline: 'Tradicional y fragante. Perfecta para la hora del té.',
    description: 'Receta de abuela actualizada. El membrillo aporta su aroma característico y su color dorado, mientras la pera suaviza el sabor y la textura. Ideal para acompañar quesos y fiambres como el dulce de membrillo pero con más frescura.',
    ingredients: ['Membrillo', 'Pera', 'Azúcar', 'Jugo de limón'],
    uses: ['Hora del té con scones', 'Con queso port salut o pategrás', 'Sobre medialunas', 'En tablas de fiambres'],
    season: 'Otoño · Marzo a Mayo',
  },
  {
    id: 'mermelada-manzana-pera',
    name: 'Mermelada de Manzana y Pera',
    category: 'mermelada',
    icon: '🍎',
    image: null,
    price: 6000,
    weight: '360 cc',
    tagline: 'Suave y dulce. Un clásico de otoño.',
    description: 'La combinación más clásica del otoño. Manzanas y peras de estación cocinadas hasta obtener una mermelada de color dorado, suave y delicadamente perfumada. Perfecta para toda la familia.',
    ingredients: ['Manzana', 'Pera', 'Azúcar', 'Jugo de limón'],
    uses: ['Tostadas del desayuno', 'Relleno de tartas', 'Con avena y granola', 'Para los más chicos'],
    season: 'Otoño · Marzo a Junio',
  },

  // ── CONSERVAS ──────────────────────────────────────────────
  {
    id: 'conserva-alcauciles',
    name: 'Alcauciles en Conserva',
    category: 'conserva',
    icon: '🌸',
    image: null,
    price: 4500,
    weight: '360 cc / 660 cc',
    variants: [
      { label: '360 cc', price: 4500 },
      { label: '660 cc', price: 8000 },
    ],
    tagline: 'Tiernos y sabrosos. En aceite de oliva y hierbas.',
    description: 'Alcauciles frescos y tiernos, cocidos al punto justo y conservados en aceite de oliva con ajo, laurel y hierbas aromáticas. Listos para usar directamente del frasco.',
    ingredients: ['Alcauciles frescos', 'Aceite de oliva', 'Ajo', 'Laurel', 'Sal', 'Vinagre de vino'],
    uses: ['Antipastos y entradas', 'En pizzas artesanales', 'Con pasta fresca', 'Tablas de fiambres'],
    season: 'Primavera · Agosto a Octubre',
  },
  {
    id: 'conserva-pepinillos',
    name: 'Pepinillos en Escabeche',
    category: 'conserva',
    icon: '🥒',
    image: 'assets/img/producto_pepinillos1.jpg',
    price: 4500,
    weight: '360 cc / 660 cc',
    badge: '🥒 En temporada',
    variants: [
      { label: '360 cc', price: 4500 },
      { label: '660 cc', price: 8000 },
    ],
    tagline: 'Crocantes y acidulados. Perfectos para tablas y sándwiches.',
    description: 'Pepinillos pequeños y crocantes encurtidos en vinagre con semillas de mostaza, eneldo y especias seleccionadas. La textura crujiente se mantiene intacta gracias a nuestro proceso artesanal.',
    ingredients: ['Pepinillos frescos', 'Vinagre de vino blanco', 'Semillas de mostaza', 'Eneldo', 'Sal', 'Azúcar'],
    uses: ['Sándwiches y hamburguesas', 'Tablas de fiambres y quesos', 'Picadas', 'Acompañamiento de asados'],
    season: 'Verano · Noviembre a Febrero',
  },
  {
    id: 'conserva-morrones',
    name: 'Morrones Asados',
    category: 'conserva',
    icon: '🫑',
    image: 'assets/img/producto_morrones.png',
    price: 4500,
    weight: '360 cc / 660 cc',
    variants: [
      { label: '360 cc', price: 4500 },
      { label: '660 cc', price: 8000 },
    ],
    tagline: 'Asados y marinados. Dulces y ahumados.',
    description: 'Morrones rojos y amarillos asados a la llama, pelados a mano y marinados en aceite de oliva con ajo y hierbas. Su sabor dulce y ahumado transforma cualquier plato.',
    ingredients: ['Morrón rojo y amarillo', 'Aceite de oliva', 'Ajo', 'Hierbas aromáticas', 'Sal', 'Vinagre'],
    uses: ['Antipastos', 'En focaccia o pizzas', 'Con huevos y jamón', 'Ensaladas mediterráneas'],
    season: 'Verano · Enero a Marzo',
  },
  {
    id: 'conserva-ajies',
    name: 'Ajíes en Conserva',
    category: 'conserva',
    icon: '🌶️',
    image: 'assets/img/producto_aji_vinagre.png',
    price: 4500,
    weight: '360 cc / 660 cc',
    variants: [
      { label: '360 cc', price: 4500 },
      { label: '660 cc', price: 8000 },
    ],
    tagline: 'Con el picante justo. Para los amantes del sabor intenso.',
    description: 'Ajíes frescos conservados en vinagre y aceite, con un nivel de picante equilibrado. Ideales para añadir un toque de intensidad a tus platos sin abrumar el paladar.',
    ingredients: ['Ajíes frescos', 'Aceite de girasol', 'Vinagre', 'Ajo', 'Sal', 'Especias'],
    uses: ['Picadas y antipastos', 'Con asado y parrilla', 'En empanadas y tartas', 'Relleno de pizzas'],
    season: 'Verano · Diciembre a Marzo',
  },
  {
    id: 'conserva-ajos',
    name: 'Ajos en Aceite',
    category: 'conserva',
    icon: '🧄',
    image: null,
    price: 6000,
    weight: '250 g',
    tagline: 'En aceite y hierbas. Sabor concentrado e intenso.',
    description: 'Dientes de ajo enteros o en mitades, confitados en aceite de oliva con hierbas aromáticas. Suaves y perfumados, listos para usar en todo tipo de preparaciones.',
    ingredients: ['Ajo fresco', 'Aceite de oliva', 'Romero', 'Tomillo', 'Pimienta en grano', 'Sal'],
    uses: ['Sofritos y guisos', 'Untado en pan tostado', 'En pastas y arroces', 'Marinadas para carnes'],
    season: 'Todo el año',
  },
  {
    id: 'conserva-tomates-secos',
    name: 'Tomates Secos',
    category: 'conserva',
    icon: '☀️',
    image: null,
    price: 4500,
    weight: '360 cc / 660 cc',
    variants: [
      { label: '360 cc', price: 4500 },
      { label: '660 cc', price: 8000 },
    ],
    tagline: 'Deshidratados con sal y aceite. Sabor intenso y mediterráneo.',
    description: 'Tomates deshidratados lentamente y conservados en aceite de oliva. Concentran todo el sabor del tomate fresco multiplicado por diez. Un ingrediente gourmet para elevar tus platos.',
    ingredients: ['Tomate perita', 'Aceite de oliva', 'Sal gruesa', 'Orégano', 'Ajo'],
    uses: ['En focaccias y pizzas', 'Con pasta fresca', 'En ensaladas y tartas', 'Antipastos gourmet'],
    season: 'Verano · Enero a Marzo',
  },
  {
    id: 'conserva-berenjenas',
    name: 'Berenjenas en Escabeche',
    category: 'conserva',
    icon: '🍆',
    image: null,
    price: 4500,
    weight: '360 cc / 660 cc',
    variants: [
      { label: '360 cc', price: 4500 },
      { label: '660 cc', price: 8000 },
    ],
    tagline: 'En escabeche o en aceite. Suaves y aromáticas.',
    description: 'Berenjenas cortadas en tiras, cocinadas al punto justo y conservadas en aceite con ajo, laurel y especias. Suaves al paladar, con un sabor profundo y satisfecho.',
    ingredients: ['Berenjena', 'Aceite de girasol', 'Vinagre', 'Ajo', 'Laurel', 'Orégano', 'Sal'],
    uses: ['En sándwiches y medialunas', 'Con pizza y focaccia', 'Tablas de antipastos', 'Con hummus y dips'],
    season: 'Verano · Enero a Abril',
  },
  {
    id: 'conserva-pickles',
    name: 'Pickles Mixtos',
    category: 'conserva',
    icon: '🫙',
    image: 'assets/img/producto_pickles.png',
    price: 4500,
    weight: '360 cc / 660 cc',
    variants: [
      { label: '360 cc', price: 4500 },
      { label: '660 cc', price: 8000 },
    ],
    tagline: 'Mix de verduras encurtidas. Variedad de sabores en un frasco.',
    description: 'Una mezcla colorida de verduras de estación encurtidas: zanahoria, coliflor, apio, pepinillos y más, en una salmuera especiada. Crocantes, ácidos y deliciosos.',
    ingredients: ['Pepinillo', 'Zanahoria', 'Coliflor', 'Apio', 'Vinagre', 'Sal', 'Especias'],
    uses: ['Acompañamiento de asados', 'Tablas de fiambres', 'Picadas informales', 'Hamburguesas artesanales'],
    season: 'Primavera-Verano',
  },
  {
    id: 'conserva-zapallos',
    name: 'Zapallos en Almíbar',
    category: 'conserva',
    icon: '🎃',
    image: null,
    price: 4500,
    weight: '360 cc / 660 cc',
    badge: '🎃 En temporada',
    variants: [
      { label: '360 cc', price: 4500 },
      { label: '660 cc', price: 8000 },
    ],
    tagline: 'Dulces y tiernos. Una golosina artesanal irresistible.',
    description: 'Trozos de zapallo cocidos en almíbar liviano con especias dulces. Una preparación tradicional argentina que pocos hacen ya en forma artesanal. Tiernos, dulces y muy especiales.',
    ingredients: ['Zapallo anco', 'Azúcar', 'Canela', 'Clavo de olor', 'Jugo de limón'],
    uses: ['Postre con crema o helado', 'En tartas dulces', 'Acompañando queso fresco', 'Con granola y yogur'],
    season: 'Otoño · Marzo a Mayo',
  },
  {
    id: 'conserva-chimichurri',
    name: 'Chimichurri Artesanal',
    category: 'conserva',
    icon: '🌿',
    image: null,
    price: 6000,
    weight: '250 g',
    tagline: 'La receta clásica argentina, lista para usar en el asado.',
    description: 'Chimichurri elaborado con orégano fresco, perejil, ajo, ají molido, aceite y vinagre. La receta de siempre, sin conservantes, con el sabor que recuerdas del asado del domingo.',
    ingredients: ['Orégano', 'Perejil fresco', 'Ajo', 'Ají molido', 'Aceite de oliva', 'Vinagre', 'Sal'],
    uses: ['Asado y parrilla', 'Sobre carnes grilladas', 'Para marinar pollo', 'En sándwiches de bondiola'],
    season: 'Todo el año',
  },

  // ── COMBOS ──────────────────────────────────────────────────
  {
    id: 'combo-mermelada-conserva',
    name: 'Combo Mermelada + Conserva',
    category: 'combo',
    icon: '🫙',
    image: 'assets/img/combo.jpg',
    price: 6960,
    oldPrice: 10500,
    weight: '2 × 360 cc',
    badge: '🎁 Combo',
    tagline: 'Tu mermelada y tu conserva favorita, juntas.',
    description: 'Elegí una mermelada y una conserva de nuestro catálogo completo. Dos frascos de 360 cc a precio especial. El regalo perfecto o el combo ideal para tu alacena artesanal.',
    ingredients: [],
    uses: ['Regalo artesanal', 'Degustación', 'Para la alacena', 'Ideal para regalar'],
    season: 'Todo el año',
    isCombo: true,
  },
];

function getProductById(id) {
  return PRODUCTS.find(p => p.id === id) || null;
}

function getProductsByCategory(cat) {
  const all = PRODUCTS.filter(p => p.category === cat);
  // Productos con foto primero
  return [...all.filter(p => p.image), ...all.filter(p => !p.image)];
}

function formatPrice(n) {
  return '$ ' + n.toLocaleString('es-AR');
}
